name: gpaw-raman-script
channels:
  - defaults
  - anaconda
  - conda-forge
dependencies:
  - python=3.8
  - pip=21.1
  - pillow=8.4
  - matplotlib=3.5
  - conda-forge::gpaw=22.1
  - conda-forge::ase=3.22.1
  - conda-forge::scipy=1.8
  - conda-forge::sparse=0.13
  - conda-forge::openmpi=4.1
  - conda-forge::libstdcxx-ng=12.1
  - conda-forge::c-compiler=1.4
  - conda-forge::compilers=1.4
  - conda-forge::libblas=3.8=*openblas
  - conda-forge::liblapack=3.8=*openblas
  - conda-forge::libxc=5.2
  - pip:
    - phonopy==2.11.0
    - ruamel.yaml==0.17.10
    - -e .
